### POST /suggest-dishes
POST {{BASE_URL}}/suggest-dishes
Content-Type: application/json

{
  "merchant_id": "5f4d157ed8eef50017ed8836",
  "menu_id": "menu",
  "language": "en",
  "user_preferences": {
    "preferences": [
      {
        "question": "Do you have any food allergies?",
        "answer": "No"
      },
      {
        "question": "What type of dish are you in the mood for?",
        "answer": "Main Course"
      },
      {
        "question": "Are you looking for vegetarian options?",
        "answer": "No"
      }
    ]
  }
}
