name: Deploy Lambda to ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build, tag, and push image to Amazon ECR
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: menu-advisor-model
          IMAGE_TAG: latest
        run: |
          docker build \
          --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          --build-arg DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }} \
          --build-arg MONGO_URI=${{ secrets.MONGO_URI }} \
          --build-arg DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # Deploy Lambda with updated image
      - name: Deploy Lambda function
        id: deploy-lambda
        run: |
          aws lambda update-function-code \
            --function-name menu-advisor-model \
            --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            --region ${{ secrets.AWS_REGION }}
          
          aws lambda update-function-configuration \
            --function-name menu-advisor-model \
            --environment "Variables={OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }},MONGO_URI=${{ secrets.MONGO_URI }},DATABASE_NAME=${{ secrets.DATABASE_NAME }}" \
            --region ${{ secrets.AWS_REGION }}
